import { useCallback, useEffect, useState } from "react";
import type { Wallpaper } from "./types";

/** Wallpaper registry. Slugs match the files generated by
 * scripts/gen-wallpapers.py into web/public/wallpaper/. Add a new wallpaper
 * there and append here to expose it in the picker. */
export const WALLPAPERS: Wallpaper[] = [
  { slug: "foggy-forest", label: "Foggy Forest", src: "/wallpaper/foggy-forest.jpg", thumb: "/wallpaper/foggy-forest-thumb.jpg" },
  { slug: "golden-hour", label: "Golden Hour", src: "/wallpaper/golden-hour.jpg", thumb: "/wallpaper/golden-hour-thumb.jpg" },
  { slug: "city-in-the-clouds", label: "City in the Clouds", src: "/wallpaper/city-in-the-clouds.jpg", thumb: "/wallpaper/city-in-the-clouds-thumb.jpg" },
  { slug: "summer-sea", label: "Summer Sea", src: "/wallpaper/summer-sea.jpg", thumb: "/wallpaper/summer-sea-thumb.jpg" },
  { slug: "petals-of-the-moon", label: "Petals of the Moon", src: "/wallpaper/petals-of-the-moon.jpg", thumb: "/wallpaper/petals-of-the-moon-thumb.jpg" },
  { slug: "sunset-ocean", label: "Sunset Ocean", src: "/wallpaper/sunset-ocean.jpg", thumb: "/wallpaper/sunset-ocean-thumb.jpg" },
  { slug: "mountain-glow", label: "Mountain Glow", src: "/wallpaper/mountain-glow.jpg", thumb: "/wallpaper/mountain-glow-thumb.jpg" },
  { slug: "spring-garden", label: "Spring Garden", src: "/wallpaper/spring-garden.jpg", thumb: "/wallpaper/spring-garden-thumb.jpg" },
  { slug: "impression-sunrise", label: "Impression, Sunrise", src: "/wallpaper/impression-sunrise.jpg", thumb: "/wallpaper/impression-sunrise-thumb.jpg" },
  { slug: "seine-spring", label: "Spring by the Seine", src: "/wallpaper/seine-spring.jpg", thumb: "/wallpaper/seine-spring-thumb.jpg" },
];

export const DEFAULT_WALLPAPER_SLUG = "foggy-forest";

const STORAGE_KEY = "homepage.wallpaper";

/** Custom event dispatched on same-tab slug changes so multiple
 *  useWallpaper() call-sites stay in sync without a context provider. */
const WALLPAPER_CHANGE = "homepage:wallpaper-change";

function readStoredSlug(): string {
  try {
    const v = window.localStorage.getItem(STORAGE_KEY);
    if (v && WALLPAPERS.some((w) => w.slug === v)) return v;
  } catch {
    /* ignore (private mode / disabled storage) */
  }
  return DEFAULT_WALLPAPER_SLUG;
}

export function wallpaperBySlug(slug: string): Wallpaper {
  return WALLPAPERS.find((w) => w.slug === slug) ?? WALLPAPERS[0];
}

/** Wallpaper selection persisted to localStorage. */
export function useWallpaper(): {
  wallpaper: Wallpaper;
  setSlug: (slug: string) => void;
} {
  const [slug, setSlugState] = useState<string>(() => readStoredSlug());

  const setSlug = useCallback((next: string) => {
    setSlugState(next);
    try {
      window.localStorage.setItem(STORAGE_KEY, next);
    } catch {
      /* ignore */
    }
    // Dispatch custom event so other useWallpaper() call-sites in the same
    // tab pick up the change immediately (cross-tab sync is via storage event).
    window.dispatchEvent(new CustomEvent(WALLPAPER_CHANGE, { detail: next }));
  }, []);

  // keep multiple tabs in sync via storage event + same-tab via custom event
  useEffect(() => {
    const onStorage = (e: StorageEvent) => {
      if (e.key === STORAGE_KEY && e.newValue) setSlugState(e.newValue);
    };
    const onCustom = (e: Event) => {
      const slug = (e as CustomEvent).detail as string;
      if (slug) setSlugState(slug);
    };
    window.addEventListener("storage", onStorage);
    window.addEventListener(WALLPAPER_CHANGE, onCustom);
    return () => {
      window.removeEventListener("storage", onStorage);
      window.removeEventListener(WALLPAPER_CHANGE, onCustom);
    };
  }, []);

  return { wallpaper: wallpaperBySlug(slug), setSlug };
}

/* ---- Optional decorative wallpaper layer --------------------------------
   Off by default: the canvas is the paper + grid + beam look. Enabling paints
   the selected wallpaper softly behind the grid so ink UI stays readable. */
const ENABLED_KEY = "homepage.wallpaper.enabled";
const ENABLE_CHANGE = "homepage:wallpaper-enable-change";

function readEnabled(): boolean {
  try {
    return window.localStorage.getItem(ENABLED_KEY) === "1";
  } catch {
    return false;
  }
}

export function useWallpaperEnabled(): {
  enabled: boolean;
  setEnabled: (v: boolean) => void;
} {
  const [enabled, setEnabledState] = useState<boolean>(() => readEnabled());

  const setEnabled = useCallback((next: boolean) => {
    setEnabledState(next);
    try {
      window.localStorage.setItem(ENABLED_KEY, next ? "1" : "0");
    } catch {
      /* ignore */
    }
    window.dispatchEvent(new CustomEvent(ENABLE_CHANGE, { detail: next }));
  }, []);

  useEffect(() => {
    const onStorage = (e: StorageEvent) => {
      if (e.key === ENABLED_KEY && e.newValue != null) setEnabledState(e.newValue === "1");
    };
    const onCustom = (e: Event) => {
      const v = (e as CustomEvent).detail as boolean;
      setEnabledState(v);
    };
    window.addEventListener("storage", onStorage);
    window.addEventListener(ENABLE_CHANGE, onCustom);
    return () => {
      window.removeEventListener("storage", onStorage);
      window.removeEventListener(ENABLE_CHANGE, onCustom);
    };
  }, []);

  return { enabled, setEnabled };
}
